export const PAGINATION_INC = "PAGINATION_INC";
export const PAGINATION_DEC = "PAGINATION_DEC";
export const PAGINATION_PARTICULAR_PAGE = "PAGINATION_PARTICULAR_PAGE";
export const PAGINATION_RESET = "PAGINATION_RESET";